version: "3.9"

services:
  frontend:
    image: employee_management_frontend
    container_name: employee_management_frontend
    build: react-frontend/.
    restart: on-failure
    ports:
      - "3000:3000"
    # networks:
    #   - employee_management_network

  backend:
    image: employee_management_backend
    container_name: employee_management_backend
    build: springboot-backend/.
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/employee_management_system?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    # networks:
    #   - employee_management_network

  database:
    image: mysql:8.0.31
    container_name: employee_management_database
    restart: on-failure
    environment:
      MYSQL_DATABASE: employee_management_system
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - employee_management_database:/var/lib/mysql
    # networks:
    #   - employee_management_network

# networks:
#   employee_management_network:
#     name: employee_management_network

volumes:
  employee_management_database:
    name: employee_management_database
